### ISSUE TITLE
Update browser support

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#113]
- Remove Android Browser 4.4+ (Google switched to using Chrome by default instead of Android Browser in Android 4 and higher)
- Add Edge (it's separate from IE, even if it started as a fork)

**Comment by garrett** [comment]
The first version, as it's a fork from IE, which we already support. Or just say Edge? Firefox and Chrome are also kind of mostly "versionless" at this point too (with the exception of the 57 launch).

**Comment by garrett** [comment]
https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history

First version of Edge was 0.10.10049[38] (12.10049) for Windows 10.

**Comment by garrett** [comment]
They switched from 0.x releases of the browser to x.y releases at 13. However, their renderer of EdgeHTML is always a separate x.y, from 12.x - 16.x.

For simplicity, I'd say Edge 12+ (especially since it was a fork from IE 11).

**Comment by petervo** [comment]
I suggest just saying Edge, no version qualifier needed. If it works on IE 11 it should on any edge version.

**Comment by garrett** [comment]
Sure thing! Simplicity is better.

**Comment by garrett** [comment]
It'll be the only one without a version. Do versions matter for the others? (Some, yes. Most... no?)

**Comment by garrett** [comment]
(I'd suggest we also drop versions from Firefox and Chrome at a minimum, if you're comfortable with that. For Opera, they did a redo, so the version mattered. For iOS, there are devices left in the dust with old versions that just won't work. And we still need versions for IE, where it does matter.)
