### ISSUE TITLE
cockpit now available in clearlinux.org

### ISSUE THREAD

**Issue by Andy2244** [cockpit-project/cockpit-project.github.io#124]
I did poke [William Douglas](https://github.com/bryteise) over at clearlinux and he got cockpit added to the latest builds (19710+). There are still some issues, which should get solved soon.

Maybe you want to test this build and give feedback, so you can add it under supported distros on your website?
Just grab a image from the download [page](https://download.clearlinux.org/current/) and do:
`swupd bundle-add sysadmin-remote`

My org. git request is [here](https://github.com/clearlinux/clr-bundles/issues/25).

**Comment by Andy2244** [comment]
The basic stuff is now working correctly and the setup commands are this:
```
sudo swupd bundle-add sysadmin-remote
sudo systemctl enable --now cockpit.socket
```

**Comment by stefwalter** [comment]
Very cool! 

Pull requests and issues for Cockpit should go to: https://github.com/cockpit-project/cockpit ... this git repository is just for the website.

**Comment by stefwalter** [comment]
Oh whoops I see a reference to adding it to the download page. Reopening ...

**Comment by garrett** [comment]
@Andy2244: Nice!

I missed this issue while out for the holidays and implemented a pull request.

As I couldn't find a styleguide for the logo or usage*, I've fudged it all based on what I saw on clearlinux.org. It might be close enough — but please let me know if things need changing. :wink:

_*  It is "Clear Linux* OS" with the asterisk and OS, right?_

The text currently is:

---

Cockpit is in Clear Linux* OS and can be installed using `swupd`:

```
sudo swupd bundle-add sysadmin-remote
sudo systemctl enable --now cockpit.socket
```

---

I've pushed the changes to my personal fork of the repo; you can see the results @ http://garrettlesage.com/cockpit-project.github.io/running.html

@Andy2244, @bryteise, & @stefwalter: Please review the changes and the page on my staging site and let me know if it looks good or if anything needs changing.

**Comment by garrett** [comment]
Here's a screenshot of the default version of the page:

![screenshot-2018-1-17 running cockpit cockpit project 1](https://user-images.githubusercontent.com/10246/35056148-554b5be0-fbb1-11e7-897b-f9132ed38d39.png)

---

Here's a default with Clear Linux selected:

![screenshot-2018-1-17 running cockpit cockpit project 2](https://user-images.githubusercontent.com/10246/35056207-74542418-fbb1-11e7-81dd-24ec715edb3c.png)

**Comment by Andy2244** [comment]
Looks fine, but i would also add a link to [clearlinux](https://clearlinux.org) or downloads, similar to Arch User Repository, since its a bit more obscure.

**Comment by bryteise** [comment]
@garrett The astrix is just to denote that Linux isn't a term Intel owns iirc and probably doesn't make much sense to have outside of our official site/documentation so it can be dropped here. Looks great otherwise, thanks a lot!

**Comment by garrett** [comment]
I've removed the asterisk from both locations and added a link as requested in commit https://github.com/cockpit-project/cockpit-project.github.io/pull/127/commits/d5c6c87479b8307b294f17208bd5571107133d61.
