### ISSUE TITLE
Officially define Cockpit's audience

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#143]
The website does not mention the audience for Cockpit.

I talked with @andreasn yesterday and we initially came up with the following list:

1. Administrators not familiar with Linux (such as Windows admins)
2. People who are familiar with Linux, but not necessarily comfortable with administration tasks
3. Expert Linux admins who may not do everything in Cockpit, but want an easy way to check-in on their systems

There are two sub-tasks:

- [ ] Define audience (it might be similar to the above)
- [ ] Integrate audience phrasing into the website (likely on the front page in some form)

**Comment by andreasn** [comment]
Looks like a first good list to me. I think we need to discuss it more with everyone involved in the project before we go ahead and add it to the website.
I've started [a wiki page about it](https://github.com/cockpit-project/cockpit/wiki/Audience)

**Comment by stefwalter** [comment]
CC @larskarlitski

**Comment by martinpitt** [comment]
> People who are familiar with Linux, but not necessarily comfortable with administration tasks

Cockpit is all about administration tasks, so if someone isn't suitable or comfortable with changing stuff on the system, then Cockpit isn't for them either. I suppose that's not what you mean, so perhaps "comfortable with the command line and configuration files"?

**Comment by garrett** [comment]
@martinpitt: Yeah, that's what I meant — not so comfortable with command-line & configuration files.

It's basically people who could do various things by searching Google, copy/pasting random snippets from forums or StackOverflow, and crossing their fingers that bad stuff wouldn't happen. It may include people who might be experts about certain parts of the system, but perhaps not others.

**Comment by rhwood** [comment]
My employer sells RHEL 6-based clustered systems that are often, by security policies, on isolated networks and not tied into the customer's standard management systems. We frequently find that customers then:
1. have administrators who are very familiar with Windows, but not so much with Linux.
2. have a need for a lightweight dashboard/monitor across the cluster.
In both those cases, a Cockpit-like system is ideal for those customers.

**Comment by martinpitt** [comment]
@rhwood: In principle, yes; however, do note that Cockpit does not work on RHEL 6 (and it's not realistic to get it working either), due to missing systemd.

**Comment by rhwood** [comment]
@martinpitt I fully understand that Cockpit will not be on RHEL 6 (we are planning on skipping over RHEL 7 straight to RHEL 8), but its the observed audience that I wanted to bring to your attention: Windows admins with a few Linux systems they need to support.

**Comment by martinpitt** [comment]
@rhwood: Indeed, fully agreed that Windows admins are one of our focus groups. In fact, we  are trying to get a lot more feedback from seasoned Windows admins about what they expect and miss in Cockpit, as in our Linux developer circles we don't really know a lot of those.. :-)

**Comment by garrett** [comment]
Integrated in the front page, right at the top. Resolved by #373.
