### ISSUE TITLE
Blog feeds not discoverable

### ISSUE THREAD

**Issue by rhwood** [cockpit-project/cockpit-project.github.io#148]
The only way I could find that the Cockpit Blog has a feed, and what that feed URL is, was to search the closed issues on this project and find #52. Can you please make the feed more discoverable?

**Comment by garrett** [comment]
Thanks for the suggestion! It was an oversight, and one that should be fixed ASAP.

Currently:
- "RSS" shows up in a search: http://cockpit-project.org/search.html#rss (as does "atom" and "feed")
- Feed readers automatically parse the URL given and extract the Atom feed

I've made a PR (#155) that makes things more discoverable by adding the link to the feed page in the footer as well as the blog posts page.

**Comment by garrett** [comment]
@rhwood: Thanks again for pointing this out! 

We've made a few changes in PR #155 (now merged and live on the site). Hopefully this helps!

**Comment by rhwood** [comment]
Thank you, that works.
