### ISSUE TITLE
External pages should be auto-sync'd

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#151]
When external pages (on GitHub) are changed, they're not automatically pulled in.

Related PRs: #149 & #150.

Right now, `_scripts/update-external-docs.rb` needs to be manually ran. It should be run a bot (possibly the same bot as the one that updates the guide on release).

External pages are included on the site for two big reasons:
- Cohesive experience, so browsing around is not jarring
- Search integration, so the documents can be easily found when doing a search

**Comment by martinpitt** [comment]
How about we do it the other way round then, remove them from the wiki, and make the pages in this repo the primary (and only) objects?

**Comment by garrett** [comment]
That's fine too. We should move them out of /external/ if we do this.

These are the external files that are pulled in:

- external/wiki/Workflow.md
- external/wiki/Cockpit-Coding-Guidelines.md
- external/wiki/Contributing.md
- external/source/HACKING.md
- external/source/test/README.md

Wiki is from the Cockpit wiki; source is from the Cockpit source repo.

The script rewrites some URLs to make the links work as expected, so a migration should happen using the content from the files in the `external` subdirectory (after running the script, of course).

**Comment by garrett** [comment]
@martinpitt: I realized we had an open bug to get the external pages sync'd.

**Comment by martinpitt** [comment]
PR #302 is a start for this.

**Comment by martinpitt** [comment]
I sent PR #364 to fully automate this.
