### ISSUE TITLE
Ideals page has broken link

### ISSUE THREAD

**Issue by Cyb0org** [cockpit-project/cockpit-project.github.io#197]
https://cockpit-project.org/ideals.html page have link to https://cockpit-project.org/%7B%7B%20site.baseurl%20%7D%7D in the first paragraph.

**Comment by martinpitt** [comment]
I'm afraid I don't understand what you mean. What and where should this link to baseurl be?

**Comment by Cyb0org** [comment]
Just go to the ideals page and look where link for the word "Cockpit" from the first paragraph is pointing to. :)

**Comment by martinpitt** [comment]
Thanks, I see it :-)
