### ISSUE TITLE
nav: rename "try it out"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#201]
The navigation link called "Try it out" sounds like you can run a live demo in a web browser immediately.

Based on past experience, people often look for "Download" (which doesn't make sense in our case) or "Install" (which makes perfect sense for us).

I'll send a simple PR to rename the navigation item. It will intentionally not change the URL (which is used all over the place).

**Comment by garrett** [comment]
An alternative to "Install" would be "Set it up"... but install is a bit of a keyword people look for, so I think it's a stronger candidate.

**Comment by martinpitt** [comment]
"Get it"?

**Comment by larskarlitski** [comment]
> "Get it"?

Sounds a bit too much like the slang for "do you understand?" to me.

My vote is for "Install". A bit boring, but very clear.

**Comment by martinpitt** [comment]
:+1: from me
