### ISSUE TITLE
Site: broken link (404)

### ISSUE THREAD

**Issue by akaRem** [cockpit-project/cockpit-project.github.io#210]
On https://cockpit-project.org/external/wiki/Contributing.html there is a text ("User Interface / Design" section) with link ("design patterns") that leads to https://www.patternfly.org/wikis/patterns/ which is 404

**Comment by martinpitt** [comment]
I [fixed](https://github.com/cockpit-project/cockpit/wiki/Contributing/_compare/ae8e99ebb87b1b56d5db963b52b0da984c794b15...0ded2e10726a10c59640920658fcec0bf8327923) it on our actual wiki, this now needs to get synced to the web site. @garrett, you know the magic incantation for that, right?

**Comment by garrett** [comment]
All you need to do is run:

```
_scripts/update-external-docs.rb
```

...and it should update the external files. They'll need to be checked-in, of course.

I can do this on Monday, unless you'd like to fix it sooner.

**Comment by garrett** [comment]
Thanks @akaRem & @martinpitt!

The fix is applied and should be deployed on the site within a few minutes of this comment. :wink:
