### ISSUE TITLE
Overlapping of headers

### ISSUE THREAD

**Issue by harsha-iiiv** [cockpit-project/cockpit-project.github.io#212]
![screenshot 29](https://user-images.githubusercontent.com/31560965/46472733-c031ad80-c7fb-11e8-8aa2-79c805f420d6.png)

**Comment by garrett** [comment]
Thanks for reporting! Fixed a little while ago in PR https://github.com/cockpit-project/cockpit-project.github.io/pull/214 — sorry for the delay in updating this issue.
