### ISSUE TITLE
misuse of Red Hat Shadowman logo

### ISSUE THREAD

**Issue by lathan** [cockpit-project/cockpit-project.github.io#22]
In the [try it out](http://cockpit-project.org/running.html) page, the Shadowman logo is used incorrectly. There are two issues:

1. Shadowman is used without the "Red Hat" wordmark. From [brand.redhat.com](http://brand.redhat.com/logos/shadowman/):

> Our corporate logo is Shadowman and the accompanying “Red Hat” wordmark.
> We never say never, but Red Hat very seldom approves the use of the Shadowman icon alone, without the wordmark. When we do, there is always a very good reason, considered and sanctioned at the highest levels.

2. Shadowman is used to represent RHEL Atomic Host, a product of Red Hat. This is also incorrect. Again, details here: [brand.redhat.com](http://brand.redhat.com/logos/productlogos/):

**EDIT:** I'm far from an expert in this area, which is why I don't have any helpful suggestions. You should probably contact the marketing people. Some of them might be behind [this contact form](http://brand.redhat.com/feedback/).

**Comment by andreasn** [comment]
Yeah, this was a mistake from my side. I'm in contact with the Red Hat brand people to try and sort this out now. Thanks for the report!

**Comment by andreasn** [comment]
It looks like this:
![screenshot from 2015-03-27 12 18 46](https://cloud.githubusercontent.com/assets/209895/6866718/747b2a0a-d47b-11e4-8249-07666d9a6bc8.png)
