### ISSUE TITLE
Show RHEL Extras under Get it

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-project.github.io#24]
Cockpit is now in Red Hat Enterprise Linux 7 Extras
https://rhn.redhat.com/errata/RHEA-2015-0941.html

According to @stefwalter the Red Hat Atomic container we advice is not excellent, so he suggested just replacing that.

**Comment by andreasn** [comment]
Needs review

**Comment by stefwalter** [comment]
* Added sudo to subscription-manager command
     * Clarify this is on RHEL 7.1+
     * Start cockpit, not cockpit.socket
