### ISSUE TITLE
RHEL 8.0 instructions

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-project.github.io#242]
The instructions for getting Cockpit to run are for RHEL 7.4, asking you to enable extras etc.
For RHEL 8.0, only step 3 is needed, so we should probably adapt the install instructions for that.
If I recall correctly from RHEL 7.5 and up, the extras are not needed for the base packages, only for some of them.
Maybe break it up in RHEL 7 and RHEL 8 instructions?

**Comment by martinpitt** [comment]
I sent a PR: https://github.com/cockpit-project/cockpit-project.github.io/pull/244
