### ISSUE TITLE
Misleading version in "Just released" badge on front page

### ISSUE THREAD

**Issue by davidmalcolm** [cockpit-project/cockpit-project.github.io#282]
The link near the top of https://cockpit-project.org currently reads:

> Just released:
> Version 10
> 30 Oct 2019

to which this lurker thought "huh; isn't the cockpit version number much higher than that?".

Following the link shows that it's "Cockpit 206 and Cockpit-podman 10" that have just been released.

Should it use the version of cockpit?

The HTML in question is:

```
<a href="/blog/cockpit-206.html" title="Cockpit with machines, firewall, and login page improvements">
  <span class="badge-new">Just released:</span>
  <span class="badge-version">Version 10</span>
  <span class="badge-date">30 Oct 2019</span>
</a>
```

**Comment by garrett** [comment]
OH! Thanks! I need to fix the parsing. :blush:
