### ISSUE TITLE
Make anwsers to common questions very obvious

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#307]
We had someone name kapil drop by IRC today and asked a bunch of questions about Cockpit. I answered and was able to help with a better understanding and to get their system successfully set up and running.

I think the questions were all very good ones and we could enhance the website to make the answers much more obvious than they currently are. We currently do answer these, but you have to dig around a little too much.

I strongly feel we should _not_ make this a "FAQ", but integrate the Q & A into the front page of the site, in a friendly manner.

Below is a slightly formatted IRC exchange. We should polish up the gist of this and integrate it into the website soon:

## What is Cockpit?

> Cockpit is a web-based graphical interface for servers

(We answer this at the top of the web page. At this point in time on IRC, I didn't link the web page yet. I shared the link right afterward.)

## Can I install it on (distro-name-here: Arch, RHEL, Fedora, CentOS, ClearLinux, etc.)?

> Arch has Cockpit in AUR as "cockpit" https://cockpit-project.org/running.html#archlinux

> (most other distros have Cockpit in their main repos; Arch doesn't yet, AFAIK, but it's in AUR thankfully.)

kapil replied:
>> arch has cockpit in its main repository

We should update our website with this information!

## What is the difference between command line and cockpit?

> you can use both the command line and Cockpit; you can switch between them and use whatever you prefer... Cockpit uses the exact same tools you'd use on the command line

## After installing how can I access it?

> try this:  `sudo systemctl enable cockpit.socket`

> it's at https://your-hostname-or-ip-here:9090/ after installing and enabling

## Can I keep it always running?

> Cockpit doesn't run in the background; it only runs when you access it. (There's a socket that listens for connections and starts up Cockpit on-demand when you want to use it.)

## What you use cockpit for?

> you can set up and configure a server in many ways; Cockpit lets you do that with simplicity (you don't have to remember commands at a command line, for example)

> there are also applications you can install too

> but, I think most people use Cockpit to make sure the storage and networking works as they want, to check logs, to look at the hardware on a system (if they want to know exactly what's on a particular server), and a lot more

>  there's even a built-in terminal so you can access the command line from your browser (so you don't have to switch to a shell and ssh to your server)

> it's basically like a "desktop" interface, but for your server (without window management, of course)

**Comment by martinpitt** [comment]
> >  arch has cockpit in its main repository

> We should update our website with this information!

Our website is current; it was updated in commit 946924d06a17964fc7a4dd91f4f1cb626cf1a883 , and the [package search](https://www.archlinux.org/packages/?sort=&q=cockpit&maintainer=&flagged=) confirms that it's still the community repo. But that's  fine -- that repo is enabled by default. I can boot an Arch life system and run `pacman -Sy cockpit` and it works. We could add that install command to our Running page of course.

**Comment by garrett** [comment]
Resolved in #373.
