### ISSUE TITLE
highlight add-ons for Cockpit

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#348]
I don't think the website talks about https://github.com/Scribery/cockpit-session-recording, for example. We probably want to highlight Cockpit Podman a bit more as well.

Additionally, if we had instructions on how to add these in the various distros (such as adding `cockpit-session-recording` on Fedora), that would be fantastic.

**Comment by garrett** [comment]
## 1st party add-ons

Add-ons built from the Cockpit source:

- cockpit-machines
- cockpit-selinux
- cockpit-storaged
- cockpit-bridge
- cockpit-kdump
- cockpit-networkmanager
- cockpit-packagekit
- cockpit-pcp
- cockpit-selinux
- cockpit-sosreport

Add-ons externally maintained by the Cockpit & Front Door teams:

- cockpit-docker (now deprecated)
- [cockpit-podman](https://github.com/cockpit-project/cockpit-podman)
- [cockpit-ostree](https://github.com/cockpit-project/cockpit-ostree)
- [cockpit-composer](https://github.com/osbuild/cockpit-composer/)
- [cockpit-certificates](https://github.com/skobyda/cockpit-certificates)

## 2rd-party add-ons

Add-ons from other teams in Red Hat:

- [cockpit-389-ds](https://directory.fedoraproject.org/docs/389ds/download.html)
- [cockpit-session-recording](https://github.com/Scribery/cockpit-session-recording)
- [cockpit-ovirt-dashboard](https://github.com/oVirt/cockpit-ovirt)

Add-ons that are RHEL specific:

- [cockpit-subscriptions](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/new_features_system_and_subscription_management)
- cockpit-leapp (in-place upgrade tool)

**Comment by Protektor-Desura** [comment]
Here is a plugin for ZFS management
https://github.com/optimans/cockpit-zfs-manager

**Comment by Protektor-Desura** [comment]
Anyone aware of a cockpit plugin for:

MergerFS       https://github.com/trapexit/mergerfs
SnapRAID       https://github.com/amadvance/snapraid/
                      https://www.snapraid.it/

**Comment by garrett** [comment]
On the page, for every add-on, it should show:

- Title
- Homepage
- Link to issues
- Distros where it's included by default (as a package)
- Installation method? (applications page vs. package)
- Summary
- Version?
- In development vs. production?
- Official vs. third party

Then there should be groups:
1. Official Cockpit-maintained add-ons first
2. Third-party production-ready ones
3. In-development, not ready for use yet (preview add-ons)

**Comment by garrett** [comment]
@Protektor-Desura: I do see a project for cockpit-zfs-manager, but I don't see where there might be anything for Cockpit for MergerFS or SnapRAID.

The MergerFS wiki page @ https://github.com/trapexit/mergerfs/wiki/Tutorials,-Articles,-Videos,-Podcasts has a link to https://www.youtube.com/watch?v=aLyTWdzDiCg, which is a video from 2017 (so a lot of stuff has changed).

**Comment by garrett** [comment]
Meanwhile, I'm going through everything on this page and adding it as a structured data set in YAML for the website. I intend on generating a page for the website from this data. I intend on posting a PR soon.

**Comment by Protektor-Desura** [comment]
> 
> 
> @Protektor-Desura: I do see a project for cockpit-zfs-manager, but I don't see where there might be anything for Cockpit for MergerFS or SnapRAID.
> 
> The MergerFS wiki page @ https://github.com/trapexit/mergerfs/wiki/Tutorials,-Articles,-Videos,-Podcasts has a link to https://www.youtube.com/watch?v=aLyTWdzDiCg, which is a video from 2017 (so a lot of stuff has changed).

I watched the video and saw him talking about Cockpit but I didn't see anything mentioned about MergerFS or SnapRAID let alone a plugin for them for Cockpit. The video was basically an overview of cockpit for that version at the time.

**Comment by tomillr** [comment]
> Anyone aware of a cockpit plugin for:
> 
> MergerFS https://github.com/trapexit/mergerfs SnapRAID https://github.com/amadvance/snapraid/ https://www.snapraid.it/

Plugins for snapRAID and MergerFS would be great additions to Cockpit and make it a good starting point for a small NAS.
