### ISSUE TITLE
bump up Debian stable instructions

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#349]
Buster is the new stable version of Debian. [Buster's latest version of Cockpit is 188](https://www.debian.org/releases/buster/), which is [a year and a half old now](https://cockpit-project.org/blog/cockpit-188.html). People should be using a more recent version of Cockpit, so we should drop Stretch and switch it to Buster on the website.

**Comment by garrett** [comment]
@martinpitt: Debian docs state:

> All backports are deactivated by default (i.e. the packages are pinned to 100 by using ButAutomaticUpgrades: yes in the Release files. If you want to install something from backports run:
>
> `apt-get -t buster-backports install "package"`

Will `apt-get install cockpit` work? Do we need to add the `-t buster-backports` in our docs too?

**Comment by garrett** [comment]
Also, should we change the docs to be "stable" instead of "buster"? The directory exists. http://ftp.debian.org/debian/dists/stable/ I guess it might have weird results if someone is on an EOL "stable" though.

**Comment by martinpitt** [comment]
@garrett: It's http://ftp.debian.org/debian/dists/stable-backports/ actually, but yes, that works. And indeed we need to add `-t stable-backports` -- without `-t` it only worked in stretch as there was no "older" version of cockpit in the final release. We need to do something similar for [Ubuntu](https://help.ubuntu.com/community/UbuntuBackports). In general, people should have the choice between the stable and the backports version, so maybe we should show both now?

**Comment by garrett** [comment]
> people should have the choice between the stable and the backports version

Well, the stable version is a year and a half old... They'll hit bugs that have been long fixed. And come across features that just don't work (such as adding a different network type to a VM, as evidenced by today's community support session in IRC, which prompted this).

**Comment by garrett** [comment]
I've pushed a PR.

When I added a note, I realized a `<code>` block using backticks (in Markdown) would cause the flex to split the warning oddly. Therefore, I've reworked _all_ the alerts across the site to fix this layout bug and support any content. It'll be a separate commit in the PR.
