### ISSUE TITLE
Not possible to navigate between screenshots

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-project.github.io#397]
From other websites and apps, I get used to the fact that I should be able to use the arrow keys (and possibly nice semi-transparent `<` `>` overlays) to navigate between the screenshots in the gallery after opening the first one.

On the new cockpit website I have to close each screenshot after I open it and click again to get the next one.

**Comment by allisonkarlitskaya** [comment]
Bonus points: swipe-able on touchscreens.

**Comment by garrett** [comment]
I wanted to get this done for the release, but didn't want to block. I'll work on it next week.

Not only do I have a phone (don't we all?), but my personal laptop has a touchscreen too. I'll try to make swiping work in both places: mobile and desktop, after I get clicking and arrow keys implemented. It probably wouldn't be much more effort.

Thanks for opening this issue!
