### ISSUE TITLE
Needs navigation for getting to the blog

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-project.github.io#45]
The website has grown a lot of new content, so it's probably about time to add some high level navigation to it.

This needs to link to the blog (and back from it).
http://cockpit-project.org/blog/

**Comment by andreasn** [comment]
I'm thinking these nav items:
* Frontpage/logo - http://cockpit-project.org
* Blog - http://cockpit-project.org/blog/
* Try it out - http://cockpit-project.org/running.html
* Contribute - https://github.com/cockpit-project/cockpit/wiki/Contributing
* Documentation - http://cockpit-project.org/guide/latest/

**Comment by andreasn** [comment]
https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/website/navigation.png

**Comment by stefwalter** [comment]
* Release notes: http://cockpit-project.org/blog/category/release.html
 * Tutorials: http://cockpit-project.org/blog/category/tutorial.html

**Comment by garrett** [comment]
Implemented it just now. Here's a screenshot:

![cockpit-website-screenshot](https://user-images.githubusercontent.com/10246/30421748-0bc3c618-993e-11e7-9f8b-4c40bb1f80a8.png)

Sent a PR (#86).

The only thing missing is the background image for the intro (and, well, a screencast instead of a screenshot).

**Comment by garrett** [comment]
Added minor fixups after comparing screenshots in this issue.

- Now has documentation link
- Adjusted color to match @andreasn's mockup
- Rebalanced intro text

**Comment by garrett** [comment]
New screenshot:
![screenshot-2017-9-14 cockpit project cockpit project](https://user-images.githubusercontent.com/10246/30422796-466f0f36-9941-11e7-9e96-a80df7065e8e.png)

**Comment by garrett** [comment]
Staging site: http://garrettlesage.com/cockpit-project.github.io/

**Comment by andreasn** [comment]
Looks good to me!
