### ISSUE TITLE
Update installation instructions for Ubuntu backports

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#450]
It seems as though installation instructions for Ubuntu backports has changed?

See https://github.com/cockpit-project/cockpit/issues/15081#issuecomment-901311622:

> The magic incantation for Ubuntu LTS in 2021 is (as root):
>
> ```
> apt install cockpit/focal-backports
> ```
>
> Replace "focal" with the codename of your release of course if it's not LTS.

Passing the torch to @martinpitt as he has more Ubuntu experience than I do, and I'm about to go on PTO (and he should be back from PTO soon).

**Comment by martinpitt** [comment]
No, this is *not* the correct command, the `-t` option is. The linked [wiki page](https://help.ubuntu.com/community/UbuntuBackports#Enabling_Backports) describes this correctly.
