### ISSUE TITLE
Question - Where can i find the internet pages coming from the cockpit?

### ISSUE THREAD

**Issue by LucarioZilla** [cockpit-project/cockpit-project.github.io#460]
Hi, I'm trying to change some cockpit looks but I can't find the cockpit html or php file folder.
I'm currently using Ubuntu.
Someone can tell me the location of cockpit site files?

**Comment by martinpitt** [comment]
They are in /usr/share/cockpit/`<page>`/. However, that won't help you much -- these are webpacked and minified, editing these is no fun. You need to check out the sources, and modify/build from there. See https://github.com/cockpit-project/cockpit/blob/main/HACKING.md for details.

**Comment by garrett** [comment]
We have an open issue @ https://github.com/cockpit-project/cockpit/issues/16359 based on a discussion at https://github.com/cockpit-project/cockpit/discussions/16256, both related to changing the look of Cockpit — but just related to colors.

(Cockpit's branding guide is currently focused toward Linux distributions and only covers the login page and the default top color. The issue linked above is about extending it to let someone customize the look, mainly by redefining common colors.)
