### ISSUE TITLE
blog view wraps oddly

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#479]
https://garrett.github.io/cockpit-project.github.io/blog/

"Starting point" should be on the left; the wrapping is wrong. It also doesn't have a link.

**Comment by VaibhavNITK** [comment]
If this issue is still open, I'm willing to work on it.

**Comment by garrett** [comment]
Oh! I think I must've fixed this at some point. I don't see the problem.

Thanks for offering to fix it though! :+1:

**Comment by VaibhavNITK** [comment]
ok
