### ISSUE TITLE
Running: contrast of section headers is too low

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit-project.github.io#51]
The W3C [recommends][1] a contrast ratio of 4.5:1 for most text, so that it is also readable for people who have various forms of vision deficiencies.

There's a tool to check if the contrast ratio is high enough: http://webaim.org/resources/contrastchecker/?fcolor=b4b7af&bcolor=ffffff

[1]: https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

**Comment by garrett** [comment]
Fixed in #128.
