### ISSUE TITLE
Replace yum command to dnf for Fedora Installation

### ISSUE THREAD

**Issue by akinomeroglu** [cockpit-project/cockpit-project.github.io#57]
Hello,

As you know Fedora changed their package management tool a short time ago. _yum_ command is just a redirection to _dnf_ in default installation of Fedora and I think that we need to update running document to cover dnf command. I already made that change sent a pull request #56

Thanks for your effort and regards,

--
Akın

**Comment by garrett** [comment]
A big belated thanks for the fix!

Your pull request (#56) was merged in, but this issue wasn't closed yet. Closing now.
