### ISSUE TITLE
Installation instructions for Debian only list a short 32 bits PGP key id

### ISSUE THREAD

**Issue by xtaran** [cockpit-project/cockpit-project.github.io#63]
If you click on "Debian" on http://cockpit-project.org/running.html there is written:

> sudo apt-key adv --keyserver sks-keyservers.net --recv-keys **F1BAA57C**

But [using a short 32 bit key id is known to be easily forgable](https://evil32.com/) for years now.

So please change that to use at least a 64 bit key id or—even better—the complete fingerprint to fetch the key.

**Comment by martinpitt** [comment]
Fix waiting in https://github.com/cockpit-project/cockpit-project.github.io/pull/64 (not sure why github doesn't link the PR automatically).
