### ISSUE TITLE
Header on mobile

### ISSUE THREAD

**Issue by shadab15github** [cockpit-project/cockpit-project.github.io#633]
Header item should be in side bar  on mobile view
![Screenshot (20)](https://github.com/cockpit-project/cockpit-project.github.io/assets/133503907/ece70391-ca23-4594-9390-322e1d0de200)

**Comment by rufevean** [comment]
i can work on it , i can take those nav items into a hamburger menu to the right top and main logo to the left and apply it.

**Comment by garrett** [comment]
This is as designed. It should _not_ be hamburger menu. Hiding navigation in a hamburger menu in mobile is an anti-pattern.

- https://www.nngroup.com/articles/hamburger-menus/
- https://bt.ht/hamburgers/
