### ISSUE TITLE
Typo in Proxying Cockpit over NGINX

### ISSUE THREAD

**Issue by shubhit7** [cockpit-project/cockpit-project.github.io#640]
https://github.com/cockpit-project/cockpit-project.github.io/blob/27fe03d2b710a59db4c4c6e185c3f084e5c9c960/external/wiki/Proxying-Cockpit-over-NGINX.md?plain=1#LL12C23-L12C23

`Nginx is listening on on port 80 (http) and port 443 (https)`

`on` is used twice.

**Comment by martinpitt** [comment]
[Fixed in the wiki](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX/_compare/dec5eaddada105777857819dc38c679f4089bc62), thanks for pointing out! This will be automatically synced over to the website in a day or three.
