### ISSUE TITLE
Fix SSL cert SubjectAltNames for cockpit-project.org

### ISSUE THREAD

**Issue by kwill** [cockpit-project/cockpit-project.github.io#66]
**Steps to reproduce the problem:**

* Visit https://cockpit-project.org

**What should happen:**

* Same content as http://cockpit-project.org

**What happens instead:**

* SSL certificate not accepted
* Error message in Firefox:

```
cockpit-project.org uses an invalid security certificate.
The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io
Error code: SSL_ERROR_BAD_CERT_DOMAIN 
```

**Notes:**

* Visiting https://cockpit-project.github.io redirects to http://cockpit-project.org

**Comment by stellirin** [comment]
Bump, SSL needs to be fixed or users will soon get scary warnings about insecure HTTP 👎

I've used CloudFlare in the past, they have an easy solution for HTTPSifying GitHub pages with custom URLs.

**Comment by garrett** [comment]
https://cockpit-project.org/ is now served over HTTPS.

(Changes were tracked in #165.)
