### ISSUE TITLE
Search Icon on the Search Field 

### ISSUE THREAD

**Issue by sohail9972** [cockpit-project/cockpit-project.github.io#685]
Page: 

Feature : Search Icon on search field

Steps to Replicate: 
Navigate https://cockpit-project.org/search.html
In the Search filed there be Search Icon

Attachment :
<img width="960" alt="Screenshot_239" src="https://github.com/cockpit-project/cockpit/assets/68369706/c3858db9-baf0-4741-91eb-29206223ad1f">

**Comment by birendraoli** [comment]
@martinpitt I can help to solve this issue.

**Comment by jelly** [comment]
@birendraoli there is already a PR open for this issue, so I would suggest to find a different issue to solve.

**Comment by birendraoli** [comment]
@jelly Thank you.
