### ISSUE TITLE
2 new disks synchronizing 6 hours

### ISSUE THREAD

**Issue by Jongjan88** [cockpit-project/cockpit-project.github.io#709]
Synchronizing Raid 1 
6 hours? 2 new disks?

![Screenshot from 2024-02-09 17-57-35](https://github.com/cockpit-project/cockpit-project.github.io/assets/125610144/2cd0b949-ef25-463f-bdc3-6369243b0d23)

**Comment by jelly** [comment]
If you want to verify RAID array progress look at `/proc/mdstat`. But this isn't a Cockpit issue per se.

**Comment by garrett** [comment]
This also isn't a Cockpit website issue.

If you have a Cockpit-specific issue, please open on the Cockpit repo itself @ https://github.com/cockpit-project/cockpit/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
