### ISSUE TITLE
Demote or remove Cockpit-Certificates?

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-project.github.io#739]
Since we've deprecated and archived cockpit-certificates as no one from the community stepped up to maintain it, we should reflect that on the website.

The question is if we should outright remove it or keep it around.

If we keep it listed on the website, we probably want to:

1. Not include it in the list of official Cockpit extensions.
2. Have a "deprecated" badge?
3. Include a notice in the description about it being deprecated.

**Comment by martinpitt** [comment]
You are right, let's just drop it for now.
